### ISSUE TITLE
Presigned URLs for S3 downloads doesn't work with Google Cloud Storage

### ISSUE THREAD

**Issue by cpswan** [espebra/filebin2#12]
Along with my @atsign-company colleague @cconstab I've been standing up a filebin2 instance on Google Cloud, using Google Kubernetes Engine (GKE), Cloud SQL, and Google Cloud Storage (GCS). It was a pleasant surprise to find that filebin2 just worked with (GCS).

But, after the [recent change to use presigned URLS](https://github.com/espebra/filebin2/commit/4e4466e5e624865c8d95062d8b54ad4c4d5b0e91), things no longer work with GCS. Here's what I see when I click on a link to download a file:

```xml
<Error>
<Code>SignatureDoesNotMatch</Code>
<Message>The request signature we calculated does not match the signature you provided. Check your Google secret key and signing method.</Message>
<StringToSign>GET 1624537054 /test-filebin2/eb318d739823cf741ecb8aad8f27266f916ba0561198a949c45ab5f3413fe51d/e27bf9b5dafdddc15b68ba198cc4be3c8c476461f6e2dfada5f976c991ab4388</StringToSign>
</Error>

**Comment by espebra** [comment]
I'm using Minio's SDK to generate signed URLs for these GET requests. The [API for this](https://docs.min.io/docs/golang-client-api-reference#PresignedGetObject) doesn't really open for modification of the client's behavior.

I had a quick look at GCS. The V4 signing process looks to be the same. However, it seems [Google expect some Google specific headers](https://cloud.google.com/storage/docs/access-control/signing-urls-manually#algorithm) rather than (or in addition to, I'm not sure if it supports both?) the standardized amz headers that are used by AWS (and Minio for that matter).

I'm not really sure what's wrong here. Before spending more time on this - can you please double check that this issue is not due to lack of permissions in GCS?

**Comment by cpswan** [comment]
There wasn't an obvious permissions issue. In the end we went with just using an S3 bucket rather than GCS.

**Comment by espebra** [comment]
Ok, thank you for the update. As a reference; The S3 implementations I've tried with filebin (all have been successful) are Ceph (using its S3 API), Scaleway Object Storage, DigitalOcean Spaces and MinIO S3. I'll close this issue now.
