### ISSUE TITLE
Enabling CORS

### ISSUE THREAD

**Issue by lars-vc** [espebra/filebin2#15]
I wanted to use filebin to upload files to from my site and so send requests with jscript fetch, but I have attempted a couple of ways and I keep getting errors. I presume it might have to do with cors not being enabled? At least this is what I think, this curl command executes fine,
`curl --data-raw "@test.txt" -H "filename: test" https://filebin.net/ -i -L`
but when translated to a fetch command in javascript it seems to go wrong
```
await fetch("https://filebin.net", { method: "POST", body: "@test.txt", headers: { filename:"test" }});
```

**Comment by espebra** [comment]
The curl command you provided will follow a redirect, but I'm not sure if that Javascript function will. You can try to port the following curl command to javascript and see if that handles it better:

```bash
curl --data-binary "@test.txt" https://filebin.net/somecustombin/test.txt
```

If it fails due to CORS, you'll see this in the developer console of Firefox or Chrome. Can you have a look there?

**Comment by espebra** [comment]
Closing due to lack of response. Feel free to reopen if needed.
