### ISSUE TITLE
Anyone can delete anyones files

### ISSUE THREAD

**Issue by OddDevelopment** [espebra/filebin2#81]
Hello,

I noticed with your file host anyone can delete anyones files, Im not quite sure if this is intentional or not but personally I think it shouldn't be this way because if people share files semi publicly they risk trolls deleting them.

If its for a time related reason I would be happy to make a pull request and do this for you (Cookie/IP Based system depending on what you want) but I wanted to check before making anything.

Thanks,
Odd

**Comment by espebra** [comment]
Hi Odd,

It is correct that anyone knowing the URL to a bin can delete it. This is intentional and one of the deliberate design choices that are ment to mitigate abuse/malicious use and reduce the time to removal if someone comes across malicious/illegal files. I realise that is a differentiator from most, if not all, other file sharing services, and I understand that it effectively limits some use cases - for example public sharing. This is ok.

In most cases, little harm is caused by files being deleted. It is inconvenient, but not devastating. The more problematic cases would be if trolls upload other files to an existing bin or even overwrite the files that you have uploaded with malicious content. Both of these two latter scenarios can be avoided if you *lock* the bin. A locked bin will reject new file uploads and file updates, but the bin can still be deleted.

Thank you for offering to provide a PR, but for the time being it is not needed.
